# Default configuration for FraudReviwsSimulator
fraud_patterns:
  card_testing:
    orders_per_hour: 15-50
    success_rate: 0.1-0.3
    value_range: 1-100
  account_takeover:
    orders_per_hour: 1-5
    success_rate: 0.6-0.9
    value_range: 200-2000
  triangulation:
    orders_per_hour: 5-15
    success_rate: 0.4-0.7
    value_range: 100-500
  refund_abuse:
    orders_per_hour: 1-3
    success_rate: 0.8-1.0
    value_range: 150-1000

review_settings:
  suspiciousness_levels: [low, medium, high]
  product_categories:
    - Electronics
    - Home & Kitchen
    - Fashion
    - Beauty
    - Sports & Outdoors

identity_settings:
  persona_types: [low_risk, burner, sleeper_agent, premium_fraudster]
  geo_distribution:
    USA: 0.6
    NGA: 0.2
    RUS: 0.1
    CHN: 0.1